# Generated by Django 4.1.5 on 2023-01-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(default='10')),
                ('animal_type', models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('description', models.CharField(max_length=400)),
                ('slug', models.SlugField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'Pets',
            },
        ),
    ]
