# Generated by Django 4.1.5 on 2023-03-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_orderpet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunchal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujrat'), ('HR', 'Haryana'), ('HP', 'Himanchal Prdesh'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab')], default='MH', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='new', max_length=100),
        ),
    ]
