# Generated by Django 4.1.5 on 2023-03-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_state_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpet',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
    ]
